# Generated by Django 6.0.1 on 2026-01-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.CharField(default='blank', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(default='blank', max_length=100),
            preserve_default=False,
        ),
    ]
