# Generated by Django 6.0.1 on 2026-01-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_name_course_title_course_grade_course_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
